version: "3"

services:

  task5-app:
    build:
      context: ../..
      dockerfile: cmd/task5/server/Dockerfile
    image: task5-app
    container_name: task5-app
    hostname: task5-app
    env_file:
      - config/dev.app.env
    ports:
      - "12300:12300"
    networks:
      - tickets
    depends_on: [ "task5-postgres" ]

  task5-postgres:
    image: postgres:latest
    volumes:
      - ./config/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: task5-postgres
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 3000M
    env_file:
      - config/dev.database.env
    ports:
      - "5432:5432/tcp"
    networks:
      - tickets

networks:
  tickets:
    driver: bridge
